config/routes.rb
Rails.application.routes.draw do
  get "pages/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#index"
  get "play", to: "pages#play"

  resources :words do
    resources :descriptions
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/description.rb
class Description < ApplicationRecord
  belongs_to :word
  validates :description, presence: true
end

app/models/word.rb
class Word < ApplicationRecord
  has_many :descriptions, dependent: :destroy
  validates :word, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern
end

app/controllers/descriptions_controller.rb
class DescriptionsController < ApplicationController
  def index
      @word = Word.find(params[:word_id])
      @descriptions = @word.descriptions
  end

  def new
    @word = Word.find(params[:word_id])
    @description = @word.descriptions.new
  end

  def create
    @word = Word.find(params[:word_id])
    @description = @word.descriptions.create(description_params)
    redirect_to word_path(@word)
  end

  def edit
    @word = Word.find(params[:word_id])
    @description = @word.descriptions.find(params[:id])
  end

  def update
    @word = Word.find(params[:word_id])
    @description = @word.descriptions.find(params[:id])
    if @description.update(description_params)
      redirect_to word_path(@word)
    else
      redirect_to word_path(@word), status: :unprocessable_entity
    end
  end

  def destroy
    @word = Word.find(params[:word_id])
    @description = @word.descriptions.find(params[:id])
    @description.destroy
    redirect_to word_path(@word), status: :see_other
  end

  private
    def description_params
      params.require(:description).permit(:description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def play
    @words = Word.all
    lenght = @words.length
    @word = @words[rand(lenght)]
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @words = Word.all
  end

  def show
    @word = Word.find(params[:id])
  end

  def new
    @word = Word.new
  end

  def create
    @word = Word.new(word_params)
    if @word.save
      redirect_to @word
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @word = Word.find(params[:id])
  end

  def update
    @word = Word.find(params[:id])

    if @word.update(word_params)
      redirect_to @word
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @word = Word.find(params[:id])
    @word.destroy

    redirect_to words_path, status: :see_other
  end

  private
    def word_params
      params.require(:word).permit(:word)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/descriptions_helper.rb
module DescriptionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/descriptions/_delete.html.erb
<span>
    <%= link_to "Delete", [description.word, description],
    class: "mt-2 bg-gray-100 inline-block border px-2 py-1 rounded-md hover:bg-red-500 active:bg-red-600 hover:text-white active:text-white active:scale-95",
    data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
    } %>
</span>

app/views/descriptions/_descriptions.html.erb
<% if @descriptions.any? %>
    <ul>
        <% @descriptions.each do |description| %>
            <li>
                <%= description.description %>
            </li>
        <% end %>
    </ul>
<% else %>
    <p>There are no descriptions.</p>
<% end %>

app/views/descriptions/_edit_form.html.erb
<%= form_with model: [@word, description] do |form| %>
    <div>
        <% if description.new_record? %>
            <%= form.label :description, "How do you want to describe the word?"%><br>
        <% end %>
        <%= form.text_area :description, class: "rounded-md w-full" %>
        <% description.errors.full_messages_for(:description).each do |message| %>
            <div class="text-red-500"><%= message %></div>
        <% end %>
    </div>
    <div class="mt-2 *:bg-blue-500 *:px-8 *:py-2 *:rounded-md *:text-white *:hover:bg-blue-400 *:active:bg-blue-600 *:active:scale-95 *:cursor-pointer">
        <%= form.submit "Save" %>
    </div>
<% end%>

app/views/descriptions/_form.html.erb
 <%= form_with model: [ @word, Description.new(word: @word) ] do |form| %>
    <p>
        <%= form.label :description, "How do you want to describe the word?" %><br>
        <%= form.text_field :description, class: "mt-4 rounded-md w-full" %>
    </p>
    <p class="mt-2 *:bg-blue-500 *:px-8 *:py-2 *:rounded-md *:text-white *:hover:bg-blue-400 *:active:bg-blue-600 *:active:scale-95 *:cursor-pointer">
        <%= form.submit "Save" %>
    </p>
<% end %>

app/views/descriptions/index.html.erb
<div class="max-w-[600px] mx-auto px-2 py-2 sm:px-0">
    
    <h1 class="text-4xl mb-8">Descriptions for <%= @word.word %></h1>

    <%= render "descriptions" %>

</div>

app/views/descriptions/new.html.erb
<div class="max-w-[600px] mx-auto px-2 py-2 sm:px-0">
    
    <h1 class="text-4xl mb-8">Descriptions for <%= @word.word %></h1>

     <%= form_with model: [ @word, Description.new(word: @word) ] do |form| %>
        <p>
            <%= form.label :description, "How do you want to describe the word?" %><br>
            <%= form.text_field :description, class: "mt-1 rounded-md w-full" %>
        </p>
        <p class="mt-2 *:bg-blue-500 *:px-8 *:py-2 *:rounded-md *:text-white *:hover:bg-blue-400 *:active:bg-blue-600 *:active:scale-95 *:cursor-pointer">
            <%= form.submit "Save" %>
        </p>
    <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Charades" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="min-h-screen overflow-y-scroll">
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/_back.html.erb
<nav class="fixed top-0 left-0 h-[48px] w-full flex justify-between items-center px-2 sm:px-16">
    <%= link_to "Back", "/",
        class: "inline-block border rounded-md px-2 py-1 hover:bg-gray-200 active:bg-gray-300 active:scale-95"
        %>
</nav>

app/views/pages/_finish.html.erb
<nav class="fixed top-0 left-0 h-[48px] w-full flex justify-between items-center px-2 sm:px-16">
    <%= link_to "Finish", "/",
        class: "inline-block border rounded-md px-2 py-1 hover:bg-gray-200 active:bg-gray-300 active:scale-95"
        %>
</nav>

app/views/pages/index.html.erb
<div class="p-2 py-[48px] sm:p-0 sm:py-[48px] max-w-[600px] mx-auto">
    <h1 class="text-4xl mb-4">Welcome to ESL Charades</h1>
    <p class="mb-8">Challenge your students to describe and guess words.</p>
    <a href="/play" class="bg-blue-500 text-white px-8 py-2 rounded-md inline-block hover:bg-blue-600 active:bg-blue-700 active:scale-95">Play Now</a>
    <a href="/words" class="border px-8 py-2 rounded-md inline-block hover:bg-gray-200 active:bg-gray-300 active:scale-95">Words</a>
    <hr class="my-8"/>
    <h2 class="text-2xl mb-4">How to Play</h2>
    <ol class="list-decimal list-inside">
        <li class="mb-2">Choose a student (or students) to guess the word.</li>
        <li class="mb-2">Don't let them see! Face them away from the screen or have them close their eyes.</li>
        <li class="mb-2">Choose a different student (or students) to read the word descriptions.</li>
        <li class="mb-2">Give your students some time to guess before reading the next description.</li>
        <li class="mb-2">Ran out of descriptions? Call hands to let your students make their own descriptions.</li>
    </ol>
</div>

app/views/pages/play.html.erb
<%= render "finish" %>
<% if @word %>
    <div class="h-screen grid">
        <div class="grid place-content-center">
            <p class="text-center text-5xl mt-[48px]"><%= @word.word %></p>
        </div>
        <div class="grid grid-rows-4 text-xl">
        <% if @word.descriptions.any? %>
            <ul class="row-span-3 flex items-stretch overflow-x-scroll no-scrollbar border-y border-black">
                <% @word.descriptions.each do |description| %>
                    <li class="w-full flex-shrink-0 text-5xl px-2 py-2 sm:px-16 sm:py-16 sm:text-center">
                        <%= description.description %>
                    </li>
                <% end %>
            </ul>
            <p class="text-center text-gray-700">Scroll left and right to change descriptions</p>
        <% else %>
            <p class="text-center mb-2">There are no descriptions for this word.</p>
            <%= link_to "Add descriptions", word_path(@word), 
            class: "underline underline-offset-2 hover:text-blue-500 active:scale-95 duration-200 ease-in-out" %>
        <% end %>
        </div>
        <p class="text-center grid place-content-center">
            <button 
            onclick="window.location.reload()" 
            class="bg-blue-500 text-white px-8 py-2 rounded-md inline-block hover:bg-blue-600 active:bg-blue-700 active:scale-95">
                Get New Word
            </button>
        </p>
    </div>
<% else %>
    <div class="h-screen grid place-content-center px-2 sm:px-0 text-xl">
        <h1 class="text-4xl mb-4">There are no words saved!</h1>
        <p class="mb-4">Add words before you can play.</p>
        <a href="/words/new" class="underline underline-offset-2 hover:text-blue-500 active:scale-95 duration-200 ease-in-out">Add New Word</a>
    </div>
<% end%>

app/views/words/_delete.html.erb
<%= link_to "Delete", word_path(@word),
    class: "mt-8 inline-block border px-8 py-2 rounded-md hover:bg-red-500 active:bg-red-600 hover:text-white active:text-white active:scale-95",
    data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
    } %>

app/views/words/_form.html.erb
<%= form_with model: @word do |form| %>
    <div>
        <% if @word.new_record? %>
            <%= form.label :word, "What word do you want to add?"%><br>
        <% else %>
            <%= form.label :word, "Update the word to fix any mistakes."%><br>
        <% end %>
        <%= form.text_field :word, class: "mt-4 rounded-md w-full" %>
        <% word.errors.full_messages_for(:word).each do |message| %>
            <div class="text-red-500"><%= message %></div>
        <% end %>
    </div>
    <div class="mt-2 *:bg-blue-500 *:px-8 *:py-2 *:rounded-md *:text-white *:hover:bg-blue-400 *:active:bg-blue-600 *:active:scale-95 *:cursor-pointer">
        <%= form.submit "Save" %>
    </div>
<% end%>

app/views/words/edit.html.erb
<div class="p-2 py-[48px] sm:p-0 sm:py-[48px] max-w-[600px] mx-auto">
    <%= link_to "Back", word_path(@word),
        class: "inline-block border rounded-md px-2 py-1 hover:bg-gray-200 active:bg-gray-300 active:scale-95"
        %>

    <h1 class="text-4xl mb-4 mt-8">Edit Word</h1>

    <%= render "form", word: @word %>
</div>

app/views/words/index.html.erb
<div class="p-2 py-[48px] sm:p-0 sm:py-[48px] max-w-[600px] mx-auto">
    <a href="/" class="border rounded-md px-2 py-1 hover:bg-gray-200 active:bg-gray-300 active:scale-95">Back</a>
    <h1 class="text-4xl mb-4 mt-8">ESL Charades Words</h1>
    <p class="mb-4">The words you want aren't in the list? You are welcome to add more words any time.</p>
    <%= link_to "New Word", new_word_path,
        class: "bg-blue-500 px-8 py-2 rounded-md text-white hover:bg-blue-600 active:bg-blue-700 active:scale-95 inline-block" %>
    <hr class="my-8"/>
    <h2 class="text-4xl mb-4">Words</h2>
    <p class="mb-4">Look through all the words available in the app. Please use the link above to add any words you can't find.</p>
    <% if @words.any? %>
    <ul>
        <% @words.each do |word| %>
            <li>
                <%= link_to word.word, word%>
            </li>
            <hr class="my-2"/>
        <% end %>
    </ul>
    <% else %>
    <p>There are no words.</p>
    <% end %>


</div>

app/views/words/new.html.erb
<div class="p-2 py-[48px] sm:p-0 sm:py-[48px] max-w-[600px] mx-auto">
    <%= link_to "Back", "/words",
        class: "inline-block border rounded-md px-2 py-1 hover:bg-gray-200 active:bg-gray-300 active:scale-95"%>
    
    <h1 class="text-4xl mb-4 mt-8">New Word</h1>

    <%= render "form", word: @word %>

</div>

app/views/words/show.html.erb
<nav class="fixed top-0 left-0 h-[48px] w-full flex justify-between items-center px-2 sm:px-16">
    <a href="/words" class="inline-block border rounded-md px-2 py-1 hover:bg-gray-200 active:bg-gray-300 active:scale-95">Back</a>
</nav>
<div class="p-2 py-[48px] sm:px-16 sm:py-[48px] grid gap-8 sm:gap-16 sm:grid-cols-3">
    <div>
        <turbo-frame id="<%= @word.id %>">
            <h1 class="text-4xl mb-2"><%= @word.word %></h1>
            <%= render "form", word: @word, method: :patch %>
            <%= render "delete", word: @word %>
        </turbo-frame>
    </div>
    <turbo-frame id="descriptions" class="col-span-2">
        <div class="grid sm:grid-cols-2 gap-8 sm:gap-16">
            <div>
                <h2 class="text-4xl mb-2">Describe it</h2>
                <%= render "descriptions/form", word: @word,  method: :post %>
            </div>
            <div>
                <h2 class="text-4xl mb-2">Descriptions</h2>
                <p class="mb-4">Update the descriptions if they don't fit right.</p>
                <% if @word.descriptions.any? %>
                    <ul class="grid gap-4">
                        <% @word.descriptions.order('created_at DESC').each do |description| %>
                            <li>
                                <turbo-frame id="description_<%= description.id%>">
                                    <%= render "descriptions/edit_form", word: @word, description: description%>
                                </turbo-frame>
                                <%= render "descriptions/delete", description: description  %>
                            </li>
                            <hr />
                        <% end %>
                    </ul>
                <% else %>
                    <p>There are no descriptions saved!</p>
                <% end %>
            </div>
        </div>
    </turbo-frame>
    </div>
</div>